-- 1. Make the ID auto-increment so each new branch gets a unique ID
ALTER TABLE public.contacts ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.contacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 2. Make sure the branch_name column exists (in case it was missing)
ALTER TABLE public.contacts ADD COLUMN IF NOT EXISTS branch_name TEXT;

-- 3. Drop the restrictive security policy that limits it to only 'id = 1'
DROP POLICY IF EXISTS "Allow authenticated users to manage the single contact entry" ON public.contacts;

-- 4. Create a new policy that allows admins to add/edit/delete multiple branches
CREATE POLICY "Enable all access for authenticated users" 
ON public.contacts
FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');
