// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sayydwgbkspfhqixockb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNheXlkd2dia3NwZmhxaXhvY2tiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MjY5MzQsImV4cCI6MjA3MzUwMjkzNH0.9krHPCO2SULLDjaxaZEOOMw2JWBOg9IOGocua-6j2Gs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});